### ISSUE TITLE
On Version 0.1.0: java.lang.IllegalStateException: Reply already submitted 

### ISSUE THREAD

**Issue by yanivshaked** [derTuca/flutter_sim_country_code#6]
Hi,

I am getting the following error when attempting to get simCountryCode. Note that the correct value is actually returned.
Using the latest version of the plugin, 0.1.0.

2021-04-21 08:58:52.094 4734-4734/com.twtech.twelveqa E/MethodChannel#flutter_sim_country_code: Failed to handle method call
    java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
        at com.example.flutter_sim_country_code.FlutterSimCountryCodePlugin.getSimCountryCode(FlutterSimCountryCodePlugin.java:54)
        at com.example.flutter_sim_country_code.FlutterSimCountryCodePlugin.onMethodCall(FlutterSimCountryCodePlugin.java:40)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

Any suggestions? Is that safe to ignore?

**Comment by bscottsmith** [comment]
This is occurring to me also, after upgrading from 0.0.3 to 0.1.0.

**Comment by derTuca** [comment]
Please try 0.1.1.

**Comment by yanivshaked** [comment]
Thanks, issue is solved.
