### ISSUE TITLE
Unhandled Exception: PlatformException Issue

### ISSUE THREAD

**Issue by Jayvd** [derTuca/flutter_sim_country_code#7]
I get this exception whenever I call `await FlutterSimCountryCode.simCountryCode` . I am testing on real device with sim card (iPhone 11)

Any thoughts?  Thanks 

```
Unhandled Exception: PlatformException(SIM_COUNTRY_CODE_ERROR, Error getting country, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      FlutterSimCountryCode.simCountryCode (package:flutter_sim_country_code/flutter_sim_country_code.dart:10:29)
<asynchronous suspension>
```

**Comment by agnkuz** [comment]
I also have a problem with reading the country code from physical iPhone, on Android it works fine.

**Comment by moosabaloch** [comment]
I am also facing the same issue on some physical iOS Devices.

**Comment by yanivshaked** [comment]
Same here, @derTuca can you please check?
